spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password: psw1234
      jpa:
        hibernate:
          ddl-auto: create
          h2:
            console:
              enabled = true
